import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const shabnam = localFont({
  src: [
    {
      path: "../assets/fonts/Shabnam/Shabnam-Bold.woff",
      weight: "600",
      style: "bold",
    },
    {
      path: "../assets/fonts/Shabnam/Shabnam-Medium.woff",
      weight: "500",
      style: "normal",
    },
    {
      path: "../assets/fonts/Shabnam/Shabnam-Light.woff",
      weight: "400",
      style: "light",
    },
    {
      path: "../assets/fonts/Shabnam/Shabnam-Thin.woff",
      weight: "300",
      style: "thin",
    },
  ],
  variable: "--Shabnam",
});

const iranSanse = localFont({
  src: [
    {
      path: "../assets/fonts/Iranian-Sans/iranian-sans.woff",
      weight: "500",
      style: "normal",
    },
  ],
  variable: "--Irainan",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${shabnam.variable} antialiased bg-white`}>
        <div className="back-circle"></div>
        {children}
      </body>
    </html>
  );
}
